//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesco.Com.Web.SmartDelivery.OrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/MockOrderService.DataMembers")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmbientTrayCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChilledTrayCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tesco.Com.Web.SmartDelivery.OrderService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CustomerDeliveryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerOrderReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliverySlotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeliveryWithoutBagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DirectParcelCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DiscountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DropSequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DropTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrozenTrayCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GridReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tesco.Com.Web.SmartDelivery.OrderService.OrderLines[] OrderlinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScheduledArrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShortOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalOffsaledItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalSubstitutedItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WindowEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WindowStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WineTrayCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmbientTrayCount {
            get {
                return this.AmbientTrayCountField;
            }
            set {
                if ((this.AmbientTrayCountField.Equals(value) != true)) {
                    this.AmbientTrayCountField = value;
                    this.RaisePropertyChanged("AmbientTrayCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChilledTrayCount {
            get {
                return this.ChilledTrayCountField;
            }
            set {
                if ((this.ChilledTrayCountField.Equals(value) != true)) {
                    this.ChilledTrayCountField = value;
                    this.RaisePropertyChanged("ChilledTrayCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tesco.Com.Web.SmartDelivery.OrderService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CustomerDeliveryStatus {
            get {
                return this.CustomerDeliveryStatusField;
            }
            set {
                if ((this.CustomerDeliveryStatusField.Equals(value) != true)) {
                    this.CustomerDeliveryStatusField = value;
                    this.RaisePropertyChanged("CustomerDeliveryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerOrderId {
            get {
                return this.CustomerOrderIdField;
            }
            set {
                if ((this.CustomerOrderIdField.Equals(value) != true)) {
                    this.CustomerOrderIdField = value;
                    this.RaisePropertyChanged("CustomerOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerOrderReference {
            get {
                return this.CustomerOrderReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrderReferenceField, value) != true)) {
                    this.CustomerOrderReferenceField = value;
                    this.RaisePropertyChanged("CustomerOrderReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryNotes {
            get {
                return this.DeliveryNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryNotesField, value) != true)) {
                    this.DeliveryNotesField = value;
                    this.RaisePropertyChanged("DeliveryNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliverySlot {
            get {
                return this.DeliverySlotField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverySlotField, value) != true)) {
                    this.DeliverySlotField = value;
                    this.RaisePropertyChanged("DeliverySlot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DeliveryWithoutBags {
            get {
                return this.DeliveryWithoutBagsField;
            }
            set {
                if ((this.DeliveryWithoutBagsField.Equals(value) != true)) {
                    this.DeliveryWithoutBagsField = value;
                    this.RaisePropertyChanged("DeliveryWithoutBags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DirectParcelCount {
            get {
                return this.DirectParcelCountField;
            }
            set {
                if ((this.DirectParcelCountField.Equals(value) != true)) {
                    this.DirectParcelCountField = value;
                    this.RaisePropertyChanged("DirectParcelCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Discounts {
            get {
                return this.DiscountsField;
            }
            set {
                if ((this.DiscountsField.Equals(value) != true)) {
                    this.DiscountsField = value;
                    this.RaisePropertyChanged("Discounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DropSequence {
            get {
                return this.DropSequenceField;
            }
            set {
                if ((this.DropSequenceField.Equals(value) != true)) {
                    this.DropSequenceField = value;
                    this.RaisePropertyChanged("DropSequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DropTime {
            get {
                return this.DropTimeField;
            }
            set {
                if ((this.DropTimeField.Equals(value) != true)) {
                    this.DropTimeField = value;
                    this.RaisePropertyChanged("DropTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FrozenTrayCount {
            get {
                return this.FrozenTrayCountField;
            }
            set {
                if ((this.FrozenTrayCountField.Equals(value) != true)) {
                    this.FrozenTrayCountField = value;
                    this.RaisePropertyChanged("FrozenTrayCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GridReference {
            get {
                return this.GridReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.GridReferenceField, value) != true)) {
                    this.GridReferenceField = value;
                    this.RaisePropertyChanged("GridReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tesco.Com.Web.SmartDelivery.OrderService.OrderLines[] Orderlines {
            get {
                return this.OrderlinesField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderlinesField, value) != true)) {
                    this.OrderlinesField = value;
                    this.RaisePropertyChanged("Orderlines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ScheduledArrival {
            get {
                return this.ScheduledArrivalField;
            }
            set {
                if ((this.ScheduledArrivalField.Equals(value) != true)) {
                    this.ScheduledArrivalField = value;
                    this.RaisePropertyChanged("ScheduledArrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShortOrderNumber {
            get {
                return this.ShortOrderNumberField;
            }
            set {
                if ((this.ShortOrderNumberField.Equals(value) != true)) {
                    this.ShortOrderNumberField = value;
                    this.RaisePropertyChanged("ShortOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreMessage {
            get {
                return this.StoreMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreMessageField, value) != true)) {
                    this.StoreMessageField = value;
                    this.RaisePropertyChanged("StoreMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotalAmount {
            get {
                return this.SubTotalAmountField;
            }
            set {
                if ((this.SubTotalAmountField.Equals(value) != true)) {
                    this.SubTotalAmountField = value;
                    this.RaisePropertyChanged("SubTotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalOffsaledItems {
            get {
                return this.TotalOffsaledItemsField;
            }
            set {
                if ((this.TotalOffsaledItemsField.Equals(value) != true)) {
                    this.TotalOffsaledItemsField = value;
                    this.RaisePropertyChanged("TotalOffsaledItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalSubstitutedItems {
            get {
                return this.TotalSubstitutedItemsField;
            }
            set {
                if ((this.TotalSubstitutedItemsField.Equals(value) != true)) {
                    this.TotalSubstitutedItemsField = value;
                    this.RaisePropertyChanged("TotalSubstitutedItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WindowEnd {
            get {
                return this.WindowEndField;
            }
            set {
                if ((this.WindowEndField.Equals(value) != true)) {
                    this.WindowEndField = value;
                    this.RaisePropertyChanged("WindowEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WindowStart {
            get {
                return this.WindowStartField;
            }
            set {
                if ((this.WindowStartField.Equals(value) != true)) {
                    this.WindowStartField = value;
                    this.RaisePropertyChanged("WindowStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WineTrayCount {
            get {
                return this.WineTrayCountField;
            }
            set {
                if ((this.WineTrayCountField.Equals(value) != true)) {
                    this.WineTrayCountField = value;
                    this.RaisePropertyChanged("WineTrayCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/MockOrderService.DataMembers")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneDaytimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneEveningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SignaturePointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tesco.Com.Web.SmartDelivery.OrderService.CustomerCommunication customerCommunicationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFullName {
            get {
                return this.CustomerFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFullNameField, value) != true)) {
                    this.CustomerFullNameField = value;
                    this.RaisePropertyChanged("CustomerFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTitle {
            get {
                return this.CustomerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTitleField, value) != true)) {
                    this.CustomerTitleField = value;
                    this.RaisePropertyChanged("CustomerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneDaytime {
            get {
                return this.PhoneDaytimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneDaytimeField, value) != true)) {
                    this.PhoneDaytimeField = value;
                    this.RaisePropertyChanged("PhoneDaytime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneEvening {
            get {
                return this.PhoneEveningField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneEveningField, value) != true)) {
                    this.PhoneEveningField = value;
                    this.RaisePropertyChanged("PhoneEvening");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneMobile {
            get {
                return this.PhoneMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneMobileField, value) != true)) {
                    this.PhoneMobileField = value;
                    this.RaisePropertyChanged("PhoneMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SignaturePoints {
            get {
                return this.SignaturePointsField;
            }
            set {
                if ((object.ReferenceEquals(this.SignaturePointsField, value) != true)) {
                    this.SignaturePointsField = value;
                    this.RaisePropertyChanged("SignaturePoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tesco.Com.Web.SmartDelivery.OrderService.CustomerCommunication customerCommunication {
            get {
                return this.customerCommunicationField;
            }
            set {
                if ((object.ReferenceEquals(this.customerCommunicationField, value) != true)) {
                    this.customerCommunicationField = value;
                    this.RaisePropertyChanged("customerCommunication");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderLines", Namespace="http://schemas.datacontract.org/2004/07/MockOrderService.DataMembers")]
    [System.SerializableAttribute()]
    public partial class OrderLines : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSubstituedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderLineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RejectedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tesco.Com.Web.SmartDelivery.OrderService.RejectionReason RejectionReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubstitutedForField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSubstitued {
            get {
                return this.IsSubstituedField;
            }
            set {
                if ((this.IsSubstituedField.Equals(value) != true)) {
                    this.IsSubstituedField = value;
                    this.RaisePropertyChanged("IsSubstitued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderLineId {
            get {
                return this.OrderLineIdField;
            }
            set {
                if ((this.OrderLineIdField.Equals(value) != true)) {
                    this.OrderLineIdField = value;
                    this.RaisePropertyChanged("OrderLineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickedQuantity {
            get {
                return this.PickedQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.PickedQuantityField, value) != true)) {
                    this.PickedQuantityField = value;
                    this.RaisePropertyChanged("PickedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RejectedQuantity {
            get {
                return this.RejectedQuantityField;
            }
            set {
                if ((this.RejectedQuantityField.Equals(value) != true)) {
                    this.RejectedQuantityField = value;
                    this.RaisePropertyChanged("RejectedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tesco.Com.Web.SmartDelivery.OrderService.RejectionReason RejectionReason {
            get {
                return this.RejectionReasonField;
            }
            set {
                if ((this.RejectionReasonField.Equals(value) != true)) {
                    this.RejectionReasonField = value;
                    this.RaisePropertyChanged("RejectionReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubstitutedFor {
            get {
                return this.SubstitutedForField;
            }
            set {
                if ((object.ReferenceEquals(this.SubstitutedForField, value) != true)) {
                    this.SubstitutedForField = value;
                    this.RaisePropertyChanged("SubstitutedFor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerCommunication", Namespace="http://schemas.datacontract.org/2004/07/MockOrderService.DataMembers")]
    [System.SerializableAttribute()]
    public partial class CustomerCommunication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommunicationDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CommunicationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommunicationDetail {
            get {
                return this.CommunicationDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationDetailField, value) != true)) {
                    this.CommunicationDetailField = value;
                    this.RaisePropertyChanged("CommunicationDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CommunicationTime {
            get {
                return this.CommunicationTimeField;
            }
            set {
                if ((this.CommunicationTimeField.Equals(value) != true)) {
                    this.CommunicationTimeField = value;
                    this.RaisePropertyChanged("CommunicationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RejectionReason", Namespace="http://schemas.datacontract.org/2004/07/MockOrderService.DataMembers")]
    public enum RejectionReason : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Broken = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotInGoodShape = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IAppStoreOrder")]
    public interface IAppStoreOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppStoreOrder/GetCustomerOrderInfo", ReplyAction="http://tempuri.org/IAppStoreOrder/GetCustomerOrderInfoResponse")]
        Tesco.Com.Web.SmartDelivery.OrderService.Order[] GetCustomerOrderInfo(string[] orderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppStoreOrderChannel : Tesco.Com.Web.SmartDelivery.OrderService.IAppStoreOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppStoreOrderClient : System.ServiceModel.ClientBase<Tesco.Com.Web.SmartDelivery.OrderService.IAppStoreOrder>, Tesco.Com.Web.SmartDelivery.OrderService.IAppStoreOrder {
        
        public AppStoreOrderClient() {
        }
        
        public AppStoreOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppStoreOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppStoreOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppStoreOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tesco.Com.Web.SmartDelivery.OrderService.Order[] GetCustomerOrderInfo(string[] orderId) {
            return base.Channel.GetCustomerOrderInfo(orderId);
        }
    }
}
